name: Optimised CICD for springboot app

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Hello world testing
        run: echo "Hello World"
