name: Optimised CICD for springboot app

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/adv_main.yml"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: set up java sdk 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: careating  jar file and size
        run: |
          mvn -q package
          ls -lh target/*.jar

      - name: upload jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

      - name: run test cases
        run: mvn -B test -DtrimStackTrace=true
