name: CICD for java springboot app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: print hii kushal
        run: echo "hi kushal"
      
